# Generated by Django 5.0.4 on 2024-04-10 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0009_rename_imagenes_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='imagenP',
        ),
    ]
