# Generated by Django 5.0.4 on 2024-04-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0010_rename_imagen_producto_imagenp'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='img_producto/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='img_producto/'),
        ),
    ]
